TEMPLATE = app
QMAKE_STRIP =
QT += gui core widgets
CONFIG += qt warn_on console release
PREFIX = /usr
BINDIR = $$PREFIX/bin
DATADIR = $$PREFIX/share
DESTDIR = bin
OBJECTS_DIR = build
MOC_DIR = build
UI_DIR = build
FORMS = ui/ibdialog.ui
HEADERS = src/ibdimpl.h
SOURCES = src/ibdimpl.cpp src/main.cpp
target.path = $$BINDIR
desktop.path = $$DATADIR/applications/qisoburn
desktop.files += data/qisoburn.desktop
INSTALLS += target desktop
RESOURCES += qisoburn.qrc
